### PR TITLE
Report impersonation for DID did:chia:17fdhy8ya7a...

### PR DESCRIPTION
**Pull request by dexiebot**
Report `impersonation` for DID `did:chia:17fdhy8ya7a7d92cn0xzt4jlhvk7y9f60egse0ecxw7kc7s94ljlsgtgnrj`.

Reported NFT:
https://mintgarden.io/nfts/nft1h8s936uwge0hgewtxdht4mc73qgd5etd66f4dr0ug8tt7lejcssswhr9pn

Notes:
```
New collection at dexie 
Czuki - Chia Azuki
Just changed the background of someone else's collection?
```

Reported on `dexie.space`

### CODE REVIEW

**Comment by SeasonsHome** [comment]
CC0 Project

**Comment by Chreatures** [comment]
I think that the major issue is that they might go against the second point on Azuki license (https://www.azuki.com/license):
"But this license does permit you to mint and create new NFTs and NFT projects based on your Azuki NFT Art for Azuki NFTs that you own, as long as you don't use the Azuki Trademarks on"

**Comment by SeasonsHome** [comment]
I am the holder of  **Azukis on ETH**,Most cases——If the secondary creation project does not use the Azuki trademark, it should be disregarded in the community.It's also a CC0 project(Only representing myself)

**Comment by darvd29** [comment]
Thanks to everyone for contributing to the discussion!

After giving the issue much thought, the conclusion is that the situation is similar to Chunks - Chia Punks and other derivative collections. The truth is that we cannot change the world and derivative collections with more or less effort have been and will continue to emerge on all blockchains. If the creator of a collection decides to break someone else's license by copying their collection, it is only their decision (that may result in legal consequences from the original collection's creator).

This issue was already discussed quite a few times on our Discord and in other reports - a marketplace can either be an open marketplace with all its pros and cons (such as low-effort derivative collections) or a closed marketplace with a sophisticated review and endorsement process before listing. dexie as a pioneer in the Chia ecosystem is an open marketplace and anyone who mints NFT collections can freely upload offers without prior approval, which is clearly presented on NFT verification label page https://dexie.space/verifications

Our policy is to ban blatant scams, impersonations that pretend to be originals while being a copy. Here, a different collection name is used and the art is visibly (though not significantly) changed, and therefore it will not be banned for the time being, unless the original Azuki creators come with a complaint and demand to take it down. This was not an easy decision, but we don't want dexie to become a closed NFT marketplace, and thus we leave it up to the users to decide whether they want to support such collections or not.

**Pull request closed without merging**
