### PR TITLE
Report impersonation for DID did:chia:1586ml32y5x...

### PR DESCRIPTION
**Pull request by dexiebot**
Report `impersonation` for DID `did:chia:1586ml32y5xxundz6dr33luaztuwedsh4y4ndk42u6e9qctnmdsrq07e8w8`.

Reported NFT:
https://mintgarden.io/nfts/nft15grqqdsp996h3lc7ywdnycxnv7zd5qe6sv27acr2jlmcymf8uxsqrln0zu

Notes:
```
this nft has a clone from the official one

NFT Address
nft15grqqdsp996h3lc7ywdnycxnv7zd5qe6sv27acr2jlmcymf8uxsqrln0zu
NFT Minter
did:chia:1586ml32y5xxundz6dr33luaztuwedsh4y4ndk42u6e9qctnmdsrq07e8w8
```

Reported on `dexie.space`

### CODE REVIEW

**Comment by AlexClayy** [comment]
this was fake Art Apocalypse NFT
here is the official one
https://www.spacescan.io/xch/nft/collection/col14zwalksjge2zeh6h2tp5xkh770lzyh0za8f4s9hx72hk80tq0avq066zll

https://skynft.org/collection.php?COLLECTIONID=20220812102954_4439709efabb0c172f1508e9dc78d3eb

**Comment by denisu** [comment]
It's the other way around, did:chia:1586ml32y5xxundz6dr33luaztuwedsh4y4ndk42u6e9qctnmdsrq07e8w8 (@ArtApocalypseRP) is original, did:chia:1dus9fv6fxkhcm4mpf89xrj69ltfdw49gykhhs6mjlp8f20vjc4ysd347hu (@ArtApocalypsePR) is fake.

**Comment by AlexClayy** [comment]
did:chia:1dus9fv6fxkhcm4mpf89xrj69ltfdw49gykhhs6mjlp8f20vjc4ysd347hu (@ArtApocalypseRP)

are already verified on skynft marketplace
how can you define the original one and the fake one?

**Comment by denisu** [comment]
did:chia:1586ml32y5xxundz6dr33luaztuwedsh4y4ndk42u6e9qctnmdsrq07e8w8 has earlier mints. Are you the creator of ArtApocalypseRP?

**Comment by AlexClayy** [comment]
im not, and i already bought 1 from the skynft platform

**Comment by AlexClayy** [comment]
is it stolen concept or what? how can they mint the collection first?

**Comment by denisu** [comment]
I am afraid you bought a fake.

**Pull request closed without merging**
